In [1]:
import numpy as np


In [2]:
a=np.zeros(4)

In [3]:
a


array([0., 0., 0., 0.])

In [5]:
type(a[0])

numpy.float64

In [6]:
c=np.empty(10)

In [7]:
c

array([1.57155094e-311, 1.87744945e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.16095484e-028, 2.28303794e-109, 2.91237123e+257,
       4.71294503e+257, 6.80146910e-310])

In [8]:
c.dtype

dtype('float64')

In [14]:
c.shape=(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [15]:
c

array([[1.57155094e-311, 1.87744945e-322],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.16095484e-028],
       [2.28303794e-109, 2.91237123e+257],
       [4.71294503e+257, 6.80146910e-310]])

In [16]:
d=np.linspace(5,10,25)
d

array([ 5.        ,  5.20833333,  5.41666667,  5.625     ,  5.83333333,
        6.04166667,  6.25      ,  6.45833333,  6.66666667,  6.875     ,
        7.08333333,  7.29166667,  7.5       ,  7.70833333,  7.91666667,
        8.125     ,  8.33333333,  8.54166667,  8.75      ,  8.95833333,
        9.16666667,  9.375     ,  9.58333333,  9.79166667, 10.        ])

In [17]:
f=np.array((10,20,30))
f

array([10, 20, 30])

In [22]:
list=[[1,2,3,4],[1,2,3,4]]
list

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [25]:
g=np.array([list])
g

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [26]:
list

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [28]:
g.shape
?

In [30]:
h=np.random.randint(10,size=10)
h

array([1, 8, 8, 5, 7, 5, 1, 2, 0, 2])

In [31]:
h[-1]

2

In [32]:
h[0:5]

array([1, 8, 8, 5, 7])

In [33]:
h>6

array([False,  True,  True, False,  True, False, False, False, False,
       False])

In [35]:
h==8

True

In [38]:
h[h=4]

SyntaxError: invalid syntax (<ipython-input-38-aa69c473c60d>, line 1)